name: tasklist_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  equatable: ^2.0.5
  firedart: ^0.9.7
  http: ^1.2.0
  meta: ^1.12.0
  mongo_dart: ^0.10.0
  postgres: ^3.1.2
  redis: ^4.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
